version: '3.8'

services:
    app:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: ./docker/local/app.dockerfile
        volumes:
            - "./:/var/www"
            - "./docker/local/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
        networks:
            - app-network
        environment:
            XDEBUG_MODE: develop,coverage,debug,profile
            XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003

    nginx:
        platform: linux/x86_64
        build:
            context: .
            dockerfile: ./docker/local/nginx.dockerfile
        volumes:
            - "./:/var/www:delegated"
            - "./docker/local/nginx/conf.d/:/etc/nginx/conf.d/:delegated"
        depends_on:
            - "app"
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
