<?php

declare(strict_types=1);

namespace App\Controller;

use App\Model\Framework\App;

final class KRJerseyNumbersController extends AbstractController
{
    private array $playersAndNumbers = [
        2023 => [
            1 => 'Lachlan Coote',
            2 => 'Ethan Ryan',
            3 => 'Tom Opacic',
            4 => 'Shaun Kenny-Dowall',
            5 => 'Ryan Hall',
            6 => 'Roger Millward',
            7 => 'Jordan Abdull',
            8 => 'Sauaso ‘Jesse\' Sue',
            9 => 'Matt Parcell',
            10 => 'George King',
            11 => 'Frankie Halton',
            12 => 'Kane Linnett',
            13 => 'Elliot Minchella',
            14 => 'Jez Litten',
            15 => 'Rhys Kennedy',
            16 => 'James Batchelor',
            17 => 'Matty Storton',
            18 => 'Jimmy Keinhorst',
            19 => 'Will Dagger',
            20 => 'Mikey Lewis',
            21 => 'Rowan Milnes',
            22 => 'Dean Hadley',
            23 => 'Louis Senior',
            24 => 'Sam Wood',
            25 => 'Luis Johnson',
            26 => 'Sam Luckley',
            27 => 'Yusuf Aydin',
            28 => 'Will Tate',
            29 => 'Phoenix Laulu-Togaga\'e',
            30 => 'Greg Richards',
            31 => 'Zack Fishwick',
            32 => 'Connor Barley',
            33 => 'Corey Hall',
            34 => 'Jack Walker',
            35 => 'Tanguy Zenon',
            36 => 'Fouad Yaha',
            37 => 'Brad Schneider',
            38 => 'Lennie Ellis',
            39 => 'Leo Tennison',
            40 => 'Louix Gorman',
            41 => 'Cesar Rouge',
            42 => 'Isaac Shaw',
            43 => 'Luke Thomas',
            44 => 'Harvey Horne',
            45 => 'Harvey Reynolds',
            46 => 'Owen Maull',
        ],
        2022 => [
            1 => 'Lachlan Coote',
            2 => 'Ben Crooks',
            3 => 'Brad Takairangi',
            4 => 'Shaun Kenny-Dowall',
            5 => 'Ryan Hall',
            6 => 'Roger Millward',
            7 => 'Jordan Abdull',
            8 => 'Albert Vete',
            9 => 'Matt Parcell',
            10 => 'George King',
            11 => 'Dean Hadley',
            12 => 'Kane Linnett',
            13 => 'Matty Storton',
            14 => 'Jez Litten',
            15 => 'Luis Johnson',
            16 => 'Korbin Sims',
            17 => 'Elliot Minchella',
            18 => 'Jimmy Keinhorst',
            19 => 'Will Dagger',
            20 => 'Mikey Lewis',
            21 => 'Rowan Milnes',
            22 => 'Will Maher',
            23 => 'Ethan Ryan',
            24 => 'Sam Wood',
            25 => 'Greg Richards',
            26 => 'Tom Garrett',
            27 => 'Frankie Halton',
            28 => 'Will Tate',
            29 => 'Phoenix Laulu-Togaga\'e',
            30 => 'Charlie Cavanaugh',
            31 => 'Connor Moore',
            32 => 'Dan Okoro',
            33 => 'Max Kirkbright',
            34 => 'Zach Fishwick',
            35 => 'Louis Senior',
            36 => 'Sam Royle',
            37 => 'Harvey Moore',
            38 => 'Connor Barley',
        ],
        2021 => [
            1 => 'Adam Quinlan',
            2 => 'Ben Crooks',
            3 => 'Greg Minikin',
            4 => 'Shaun Kenny-Dowall',
            5 => 'Ryan Hall',
            6 => 'Roger Millward',
            7 => 'Jordan Abdull',
            8 => 'Albert Vete',
            9 => 'Matt Parcell',
            10 => 'Korbin Sims',
            11 => 'Brad Takairangi',
            12 => 'Kane Linnett',
            13 => 'Dean Hadley',
            14 => 'Jez Litten',
            15 => 'George Lawler',
            16 => 'George King',
            17 => 'Elliot Minchella',
            18 => 'Matty Storton',
            19 => 'Will Dagger',
            20 => 'Mikey Lewis',
            21 => 'Owen Harrison',
            22 => 'Nick Rawsthorne',
            23 => 'Ethan Ryan',
            24 => 'Joe Keyes',
            25 => 'Rowan Milnes',
            26 => 'Will Maher',
            27 => 'Luis Johnson',
            28 => 'Muizz Mustapha',
            29 => 'Anesu Mudoti',
            30 => 'Will Tate',
            31 => 'Thomas Whur',
            32 => 'Charlie Cavanaugh',
            33 => 'Jimmy Keinhorst',
        ],
        2020 => [
            1 => 'Adam Quinlan',
            2 => 'Ben Crooks',
            3 => 'Shaun Kenny-Dowall',
            4 => 'Kane Linnett',
            5 => 'Greg Minikin',
            6 => 'Roger Millward',
            7 => 'Jordan Abdull',
            8 => 'Robbie Mulhern',
            9 => 'Matt Parcell',
            10 => 'Mose Masoe',
            11 => 'Weller Hauraki',
            12 => 'Harvey Livett',
            13 => 'Dean Hadley',
            14 => 'Mitch Garbutt',
            15 => 'George Lawler',
            16 => 'Dan Murray',
            17 => 'Kyle Trout',
            18 => 'Jez Litten',
            19 => 'Will Dagger',
            20 => 'Mikey Lewis',
            21 => 'Owen Harrison',
            22 => 'Nick Rawsthorne',
            23 => 'Ethan Ryan',
            24 => 'Joe Keyes',
            25 => 'Matty Gee',
            26 => 'Will Maher',
            27 => 'Elliot Minchella',
            28 => 'Matty Storton',
            29 => 'Anesu Mudoti',
            30 => 'Jamie Ellis',
            31 => 'Ryan Brierley',
            32 => 'Nathaniel Peteru',
            33 => 'Will Tate',
            34 => 'Jimmy Keinhorst',
            35 => 'Rowan Milnes',
            36 => 'George King',
        ],
        2019 => [
            1 => 'Adam Quinlan',
            2 => 'Craig Hall',
            3 => 'Ben Crooks',
            4 => 'Jimmy Keinhorst',
            5 => 'Ryan Shaw',
            6 => 'Roger Millward',
            7 => 'Danny McGuire',
            8 => 'Robbie Mulhern',
            9 => 'Shaun Lunt',
            10 => 'Mose Masoe',
            11 => 'Joel Tomkins',
            12 => 'James Greenwood',
            13 => 'Weller Hauraki',
            14 => 'Mitch Garbutt',
            15 => 'Tommy Lee',
            16 => 'Lee Jewitt',
            17 => 'Chris Atkin',
            18 => 'Nick Scruton',
            19 => 'Junior Vaivai',
            20 => 'Danny Addy',
            21 => 'George Lawler',
            22 => 'Ryan Lannon',
            23 => 'Kane Linnett',
            24 => 'Josh Drinkwater',
            25 => 'Will Oakes',
            26 => 'Will Dagger',
            27 => 'Josh Johnson',
            28 => 'Elliott Wallis',
            29 => 'Joe Wardill',
            30 => 'Owen Harrison',
            31 => 'Adam Rooks',
            32 => 'Mikey Lewis',
            33 => 'Harry Bardle',
            34 => 'Antoni Maria',
            35 => 'Thomas Minns',
            36 => 'Dan Murray',
            37 => 'Harvey Livett',
            38 => 'Luis Johnson',
            39 => 'Matt Parcell',
            40 => 'Dean Hadley',
            41 => 'Jez Litten',
            42 => 'Kyle Trout',
        ],
        2018 => [
            1 => 'Adam Quinlan',
            2 => 'Junior Vaivai',
            3 => 'Thomas Minns',
            4 => 'Andrew Heffernan',
            5 => 'Ryan Shaw',
            6 => 'Roger Millward',
            7 => 'Danny McGuire',
            8 => 'Nick Scruton',
            9 => 'Shaun Lunt',
            10 => 'Mose Masoe',
            11 => 'Maurice Blair',
            12 => 'James Greenwood',
            13 => 'Ben Kavanagh',
            14 => 'Lee Jewitt',
            15 => 'James Donaldson',
            16 => 'Danny Addy',
            17 => 'Chris Clarkson',
            18 => 'George Lawler',
            19 => 'Tommy Lee',
            20 => 'Matty Marsh',
            21 => 'Robbie Mulhern',
            22 => 'Liam Salter',
            23 => 'Josh Johnson',
            24 => 'Chris Atkin',
            25 => 'Kieren Moss',
            26 => 'Joe Wardill',
            27 => 'Will Oakes',
            28 => 'Will Dagger',
            29 => 'Jordan Walne',
            30 => 'Joe Cator',
            31 => 'Brad Clavering',
            32 => 'Connor Williams',
            33 => 'Thibault Franck',
            34 => 'Danny Tickle',
            35 => 'Owen Harrison',
            36 => ' Justin Carney',
            37 => 'Elliott Wallis',
            38 => 'Aaron Smith',
            39 => 'Joel Tomkins',
            40 => 'Todd Carney',
            41 => 'Craig Hall',
            42 => 'Ben Crooks',
        ],
        2017 => [
            1 => 'Adam Quinlan',
            2 => 'Ben Cockayne',
            3 => 'Thomas Minns',
            4 => 'Liam Salter',
            5 => 'Ryan Shaw',
            6 => 'Roger Millward',
            7 => 'Jamie Ellis',
            8 => 'Nick Scruton',
            9 => 'Shaun Lunt',
            10 => 'Chris Clarkson',
            11 => 'Maurice Blair',
            12 => 'James Greenwood',
            13 => 'Danny Addy',
            14 => 'Graeme Horne',
            15 => 'James Donaldson',
            16 => 'Jordan Abdull',
            17 => 'Mitch Clark',
            18 => 'Zach Dockar-Clay',
            19 => 'George Lawler',
            20 => 'Matty Marsh',
            21 => 'Robbie Mulhern',
            22 => 'Andrew Heffernan',
            23 => 'George Milton',
            24 => 'Joe Wardill',
            25 => 'Will Jubb',
            26 => 'Kieran Moran',
            27 => 'Will Oakes',
            28 => 'Liam Harris',
            29 => 'Jake Butler-Fleming',
            30 => 'Joe Cator',
            31 => 'David Hodgson',
            32 => 'Kieren Moss',
            33 => 'Ben Kavanagh',
            34 => 'Brad Clavering',
            35 => ' Josh Johnson',
            36 => 'Justin Carney',
            37 => 'Lee Jewitt',
            38 => 'Chris Atkin',
            39 => 'Mose Masoe',
            40 => 'Jack Logan',
        ],
        2016 => [
            1 => 'Ken Sio',
            2 => 'Josh Mantellato',
            3 => 'Liam Salter',
            4 => 'Iain Thornley',
            5 => 'Kieran Dixon',
            6 => 'Terry Campese',
            7 => 'Albert Kelly',
            8 => 'Adam Walker',
            9 => 'Shaun Lunt',
            10 => 'Mitch Allgood',
            11 => 'Maurice Blair',
            12 => 'Graeme Horne',
            13 => 'Chris Clarkson',
            14 => 'Kevin Larroyer',
            15 => 'James Donaldson',
            16 => 'James Green',
            17 => 'Dane Tilse',
            18 => 'Ben Cockayne',
            19 => 'John Boudebza',
            20 => 'James Greenwood',
            21 => 'Thomas Minns',
            22 => 'Matty Marsh',
            23 => 'Ryan Shaw',
            24 => 'George Lawler',
            25 => 'Stephen Holker',
            26 => 'Robbie Mulhern',
            27 => 'Will Oakes',
            28 => 'Kieran Moran',
            29 => 'Joe Wardill',
            30 => 'Joe Cator',
            31 => 'Will Jubb',
            32 => 'Terry Campese',
            33 => 'David Thompson',
            34 => 'Jamie Peacock',
        ],
        2015 => [
            1 => 'Kieran Dixon',
            2 => 'Ben Cockayne',
            3 => 'Darrell Goulding',
            4 => 'Josh Mantellato',
            5 => 'Ken Sio',
            6 => 'Maurice Blair',
            7 => 'Albert Kelly',
            8 => 'Adam Walker',
            9 => 'Keal Carlile',
            10 => 'Mick Weyman',
            11 => 'Kevin Larroyer',
            12 => 'Graeme Horne',
            13 => 'Tyrone McCarthy',
            14 => 'Mitch Allgood',
            15 => 'James Donaldson',
            16 => 'Ryan Bailey',
            17 => 'Greg Burke',
            18 => 'Liam Salter',
            19 => 'Kris Welham',
            20 => 'James Green',
            21 => 'Aaron Ollett',
            22 => 'Jordan Cox',
            23 => 'Terry Campese',
            24 => 'John Boudebza',
            25 => 'Macauley Hallett',
            26 => 'Sonny Esslemont',
            27 => 'Josh Guzdek',
            28 => 'Connor Robinson',
            29 => 'Matty Marsh',
            30 => 'Stephen Holker',
            31 => 'Shaun Lunt',
            32 => 'Dane Tilse',
            33 => 'James Greenwood',
            34 => 'Tony Puletua',
            35 => 'Dane Chisholm',
            36 => 'George Lawler',
        ],
        2014 => [
            1 => 'Greg Eden',
            2 => 'Ben Cockayne',
            3 => 'Kris Welham',
            4 => 'Sean Gleeson',
            5 => 'David Hodgson',
            6 => 'Travis Burns',
            7 => 'Kris Keating',
            8 => 'Justin Poore',
            9 => 'Josh Hodgson',
            10 => 'Mick Weyman',
            11 => 'Kevin Larroyer',
            12 => 'Neville Costigan',
            13 => 'Jamie Langley',
            14 => 'Adam Walker',
            15 => 'Graeme Horne',
            16 => 'Jason Netherton',
            17 => 'Jonny Walker',
            18 => 'Liam Salter',
            19 => 'Craig Hall',
            20 => 'Jordan Cox',
            21 => 'Keal Carlile',
            22 => 'Rhys Lovegrove',
            23 => 'James Green',
            24 => 'Omari Caro',
            25 => 'Aaron Ollett',
            26 => 'Josh Guzdek',
            27 => 'Sonny Esslemont',
            28 => 'Matty Beharrell',
            29 => 'Connor Robinson',
            30 => 'Macauley Hallett',
            31 => 'Stephen Holker',
            32 => 'Ade Gardner',
            33 => 'Wayne Ulugia',
            34 => 'Jason Chan',
        ],
        2013 => [
            1 => 'Greg Eden',
            2 => 'Craig Hall',
            3 => 'Kris Welham',
            4 => 'Sean Gleeson',
            5 => 'David Hodgson',
            6 => 'Travis Burns',
            7 => 'Michael Dobson',
            8 => 'Evarn Tuimavave',
            9 => 'Josh Hodgson',
            10 => 'Ryan O\'Hara',
            11 => 'Con Mika',
            12 => 'Cory Paterson',
            13 => 'Rhys Lovegrove',
            14 => 'Lincoln Withers',
            15 => 'Graeme Horne',
            16 => 'Adam Walker',
            17 => 'Sam Latus',
            18 => 'Liam Salter',
            19 => 'Omari Caro',
            20 => 'Jordan Cox',
            21 => 'Keal Carlile',
            22 => 'Richard Beaumont',
            23 => 'Mickey Paea',
            24 => 'James Green',
            25 => 'George Griffin',
            26 => 'Alex Brown',
            27 => 'Chris Heil',
            28 => 'Tyla Hepi',
            29 => 'Aaron Ollett',
            30 => 'Matty Beharrell',
            31 => 'Sonny Esslemont',
            32 => 'Dale Ferguson',
            33 => 'Luke George',
            34 => 'Jason Netherton',
            35 => 'Connor Robinson',
            36 => 'Josh Guzdek',
        ],
        2012 => [
            1 => 'Shannon McDonnell',
            2 => 'Craig Hall',
            3 => 'Kris Welham',
            4 => 'Jake Webster',
            5 => 'David Hodgson',
            6 => 'Blake Green',
            7 => 'Michael Dobson',
            8 => 'Joel Clinton',
            9 => 'Josh Hodgson',
            10 => 'Scott Taylor',
            11 => 'Con Mika',
            12 => 'Ben Galea',
            13 => 'Rhys Lovegrove',
            14 => 'Lincoln Withers',
            15 => 'Liam Watts',
            16 => 'Jason Netherton',
            17 => 'Ryan O\'Hara',
            18 => 'Graeme Horne',
            19 => 'Scott Murrell',
            20 => 'Jordan Cox',
            21 => 'Sam Latus',
            22 => 'Scott Wheeldon',
            23 => 'Mickey Paea',
            24 => 'Richie Beaumont',
            25 => 'Keal Carlile',
            26 => 'George Griffin',
            27 => 'Louis Sheriff',
            28 => 'Dave Peterson',
            29 => 'Liam Salter',
            30 => 'Aaron Ollett',
            31 => 'Nick Johnson',
            32 => 'Chris Heil',
            33 => 'James Green',
            34 => 'Tyla Hepi',
            35 => 'James Laithwaite',
        ],
        2011 => [
            1 => 'Shaun Briscoe',
            2 => 'Peter Fox',
            3 => 'Kris Welham',
            4 => 'Jake Webster',
            5 => 'Liam Colbon',
            6 => 'Blake Green',
            7 => 'Michael Dobson',
            8 => 'Rhys Lovegrove',
            9 => 'Ben Fisher',
            10 => 'Joel Clinton',
            11 => 'Clint Newton',
            12 => 'Ben Galea',
            13 => 'Scott Murrell',
            14 => 'Liam Watts',
            15 => 'Scott Wheeldon',
            16 => 'Jason Netherton',
            17 => 'Matt Cook',
            18 => 'Josh Hodgson',
            19 => 'Craig Hall',
            20 => 'Mick Vella',
            21 => 'Sam Latus',
            22 => 'Scott Taylor',
            23 => 'Willie Mason',
            24 => 'Richie Beaumont',
            25 => 'Dave Peterson',
            26 => 'Louis Sheriff',
            27 => 'Jordan Cox',
            28 => 'Ben Cockayne',
        ],
        2010 => [
            1 => 'Shaun Briscoe',
            2 => 'Peter Fox',
            3 => 'Kris Welham',
            4 => 'Jake Webster',
            5 => 'Liam Colbon',
            6 => 'Paul Cooke',
            7 => 'Michael Dobson',
            8 => 'Rhys Lovegrove',
            9 => 'Scott Murrell',
            10 => 'Scott Wheeldon',
            11 => 'Clint Newton',
            12 => 'Chev Walker',
            13 => 'Ben Galea',
            14 => 'Matt Cook',
            15 => 'Mike Ratu',
            16 => 'Jason Netherton',
            17 => 'Ben Fisher',
            18 => 'David Mills',
            19 => 'Chaz I\'Anson',
            20 => 'Mick Vella',
            21 => 'Josh Hodgson',
            22 => 'Liam Watts',
            23 => 'Scott Spaven',
            24 => 'Scott Taylor',
            25 => 'Richie Beaumont',
            26 => 'Frankie Mariano',
            27 => 'Jack Latus',
            28 => 'Ben Cockayne',
            29 => 'Sam Latus',
            30 => 'Joel Clinton',
            31 => '',
            32 => 'Josh Charnley',
        ],
        2009 => [
            1 => 'Shaun Briscoe',
            2 => 'Peter Fox',
            3 => 'Chev Walker',
            4 => 'Jake Webster',
            5 => 'Liam Colbon',
            6 => 'Paul Cooke',
            7 => 'Michael Dobson',
            8 => 'Nick Fozzard',
            9 => 'Ben Fisher',
            10 => 'David Mills',
            11 => 'Clint Newton',
            12 => 'Ben Galea',
            13 => 'Scott Murrell',
            14 => 'Stanley Gene',
            15 => 'Daniel Fitzhenry',
            16 => 'Jason Netherton',
            17 => 'Makali Aizue',
            18 => 'Scott Wheeldon',
            19 => 'Kris Welham',
            20 => 'Mick Vella',
            21 => 'Chaz I\'Anson',
            22 => 'Liam Watts',
            23 => 'Ryan Esders',
            24 => 'Rhys Lovegrove',
            25 => 'Scott Spaven',
            26 => 'Frankie Mariano',
            27 => 'James Haynes',
            28 => 'Ben Cockayne',
            29 => 'Kyle Bibb',
            30 => 'Scott Taylor',
        ],
        2008 => [
            1 => 'Shaun Briscoe',
            2 => 'Peter Fox',
            3 => 'Chev Walker',
            4 => 'Jake Webster',
            5 => 'Daniel Fitzhenry',
            6 => 'Paul Cooke',
            7 => 'James Webster',
            8 => 'Garrett Crossman',
            9 => 'Ben Fisher',
            10 => 'David Mills',
            11 => 'Clint Newton',
            12 => 'Ben Galea',
            13 => 'Scott Murrell',
            14 => 'Stanley Gene',
            15 => 'Ben Cockayne',
            16 => 'Jason Netherton',
            17 => 'Makali Aizue',
            18 => 'Rhys Lovegrove',
            19 => 'Luke Menzies',
            20 => 'Mick Vella',
            21 => 'Jon Steel',
            22 => 'Kirk Netherton',
            23 => 'Chaz I\'Anson',
            24 => 'Liam Watts',
            25 => 'Kris Welham',
            26 => 'Michael Dobson',
            27 => 'Lee Gomersall',
            28 => 'Chris Chester',
        ],
        2007 => [
            1 => 'Ben Cockayne',
            2 => 'Jon Steel',
            3 => 'Jon Goddard',
            4 => 'Gareth Morton',
            5 => 'Byron Ford',
            6 => 'Scott Murrell',
            7 => 'James Webster',
            8 => 'Makali Aizue',
            9 => 'Ben Fisher',
            10 => 'David Tangata-Toa',
            11 => 'Iain Morrison',
            12 => 'Michael Smith',
            13 => 'Tommy Gallagher',
            14 => 'Stanley Gene',
            15 => 'Jim Gannon',
            16 => 'Jason Netherton',
            17 => 'Mark O\'Neill',
            18 => 'Danny Ward',
            19 => 'Matty Brooks',
            20 => 'Mick Vella',
            21 => 'Luke Dyer',
            22 => 'Andreas Bauer',
            23 => 'Pat Weisner',
            24 => 'Ian Hardman',
            25 => 'Danny Hill',
            26 => 'David Wilson',
            27 => 'Kirk Netherton',
            28 => 'Chris Chester',
            29 => 'Liam Welham',
            30 => 'Mark Lennon',
            31 => 'Paul Cooke',
            32 => 'Ryan Tandy',
            33 => 'Rhys Lovegrove',
            34 => 'Kris Welham',
            35 => 'Chaz I\'Anson',
        ],
    ];

    public function handleRequest(): App
    {
        $playersAndNumbers = $this->playersAndNumbers;
        array_walk(
            $playersAndNumbers,
            fn (array &$arr) => uksort(
                $arr,
                fn (int $k1, int $k2) => intval($k1) - intval($k2)
            )
        );
        uksort(
            $playersAndNumbers,
            fn (int $k1, int $k2) => intval($k2) - intval($k1)
        );

        $highestJersey = max(
            array_map(fn (array $arr) => count($arr), $playersAndNumbers)
        );

        $groupedPlayers = [];

        foreach ($playersAndNumbers as $year => $players) {
            for ($i = 1; $i <= $highestJersey; $i++) {
                $player = isset($players[$i]) ? $players[$i] : '';
                if (! isset($groupedPlayers[$i])) {
                    $groupedPlayers[$i] = [];
                }
                $groupedPlayers[$i][$year] = $player;
            }
        }

        $topRow = array_merge(['No.'], array_keys($groupedPlayers[1]));

        $str = $this->wrapInTags($this->wrapInTags(
            implode(
                '',
                array_map(
                    fn (string $name) => $this->wrapInTags($name, 'td'),
                    $topRow
                )
            ),
            'tr'
        ),
        'thead');

        foreach ($groupedPlayers as $jerseyNumber => $players) {
            $str .= $this->wrapInTags(
                $this->wrapInTags((string) $jerseyNumber, 'th', ['class="headcol"'])
                . implode(
                    '',
                    array_map(
                        fn (string $name) => $this->wrapInTags($name, 'td'),
                        $players
                    )
                ),
                'tr'
            );
        }

        $str = $this->wrapInTags($str, 'table');
        $this->app->view = $str;
        $this->app->style = [
            'td' => 'white-space: nowrap',
            'thead' => 'font-weight: 700',
            'tr:nth-of-type(14) > *' => 'border-top-width: 0.2rem;',
            'tr:nth-of-type(18) > *' => 'border-top-width: 0.2rem;',
            'tr' => 'background-color: white',
            'tr:nth-of-type(2n)' => 'background-color: #ffbbbb'
        ];
        return $this->app;
    }
}
